### ISSUE TITLE
How do I use xp with parameter substitution 

### ISSUE THREAD

**Issue by conikeec** [nrinaudo/kantan.xpath#90]
I am trying to use `xp` expression with a string parameter substitution ...
The code is listed below in the for loop and `xp` does not seem to work with parameter substitution.

Can you please advise as to how I can go about this?

```
import kantan.xpath._
import kantan.xpath.implicits._
import scala.collection.mutable.ListBuffer

case class Details(id : String, description : String)
case class CVE(name : String, version : String, details : List[Details])

var detailsList = new ListBuffer[Details]()

val htmlResults = scala.io.Source.fromURL("https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=jackson-databind+2.8.7").mkString

val numOfCves = htmlResults.evalXPath[Int](xp"//*[@id='CenterPane']/div[1]/b").getOrElse(0)

for (var count <- numOfCves) {
	val cveId = htmlResults.evalXPath[String](xp"//*[@id='TableWithRules']/table/tbody/tr[%d]/td[1]/a".format(count))
	val cveDescription = htmlResults.evalXPath[String](xp"//*[@id='TableWithRules']/table/tbody/tr[%d]/td[2]/text()".format(count))

	val details = Details(cveId,cveDescription)
	detailsList += details
}
```

**Comment by conikeec** [comment]
Tried this as well and it didn't work

```
val count = 10
val query = Query.compile[String]("//*[@id='TableWithRules']/table/tbody/tr[%d]/td[1]/a".format(count))
htmlResults.evalXPath(query)
```

**Comment by nrinaudo** [comment]
I'm a bit confused by this - what does "it didn't work" mean? Does it not compile? Does it compile but crash at runtime? Does it work but not produce the expected result? Something else? If any of these scenarios, what was the error message / the expected and observed behaviours / anything that could help me debug your issue?

That being said, taking a quick glance at your second example - a much better example that the first, because it doesn't contain any irrelevant code - I'd guess that your issue is that it doesn't compile, and you're not understanding the error (which should tell you that you're trying to pass a `CompileResult[Query[String]]` to a method that expects a `Query[String]`, or something along these lines).

If that's correct, then your issue is with understanding something pretty core to Scala. It's absolutely fine, and is something that you definitely should be able to get help with, but an issue in an entirely unrelated project is not the place. I'd suggest the scala/scala gitter channel, it's pretty friendly to newcomers.

If I'm not, then can you file a proper issue, defining precisely what you're expecting, what you're observing, why you feel it's a flaw in kantan.xpath and, if applicable, what suggestions you'd have for a fix?

**Comment by conikeec** [comment]
Thanks for the explanation. 
The question is simple . Rather than passing an hardcoded string literal can I pass a query string that I create based on parameter substitution . Can you point me to an example please

**Comment by nrinaudo** [comment]
Sure. Your second example does that, although it would be more idiomatic to write:
```scala
val query = Query.compile[String](s"//*[@id='TableWithRules']/table/tbody/tr[$count]/td[1]/a")
```

**Comment by conikeec** [comment]
Thank you . Appreciate it. Will try and let you know

**Comment by conikeec** [comment]
@nrinaudo Thanks for your patience to reply and suggestions and I will close the issue. 

```
val queryCompiled = Query.compile[String](s"//*[@id='TableWithRules']/table/tbody/tr[$count]/td[1]/a")
val query = queryCompiled match { case Right(x) => Some(x) ; case Left(x) => None }
htmlResults.evalXPath(query)
```

My approach is less idiomatic and elegant ..
Is there more efficient way to passed a compiled query to evalXPath

Again thanks for the awesome library and your guidance as well .

**Comment by nrinaudo** [comment]
I still don’t think that compiles - how can you pass an Option[Query[String]] to a function that expects a Query[String]?

Regardless, there are various ways to make this better. You need to read up on for comprehensions and how they allow you to chain calls that happen in the same “context”. You could also try reading th fairly extensive documentation I wrote for kantan.xpath, there’s bound to be an example in there. Or just go to scala/scala as I suggested and ask about this, it’s a fairly important tool to master when beginning scala.

**Comment by conikeec** [comment]
I solved it .. Thanks
